'use strict';

const should = require('chai').should(); // eslint-disable-line

describe('hexo-renderer-coffeescript', () => {
  const ctx = {
    config: {}
  };
  const r = require('../lib/renderer').bind(ctx);

  it('default', () => {
    const body = 'alert "hello world"';
    const result = r({text: body});

    result.should.eql([
      '(function() {',
      '  alert("hello world");',
      '',
      '}).call(this);'
    ].join('\n') + '\n');
  });

  it('bare', () => {
    ctx.config.coffee = {
      bare: true
    };

    const body = 'alert "hello world"';
    const result = r({text: body});

    result.should.eql('alert("hello world");\n');
    delete ctx.config.coffee;
  });

  it('header', () => {
    ctx.config.coffee = {
      header: true
    };

    const body = 'alert "hello world"';
    const result = r({text: body});

    result.should.contain('// Generated by CoffeeScript');

    delete ctx.config.coffee;
  });
});
